Elcodi\CartBundle\Entity\Cart:
    type: entity
    repositoryClass: Elcodi\CartBundle\Repository\CartRepository
    table: cart
    fields:
        quantity:
            column: quantity
            type: integer
        productAmount:
            column: product_amount
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        couponAmount:
            column: coupon_amount
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        amount:
            column: amount
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    oneToOne:
        order:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\OrderInterface
            mappedBy: cart

    manyToOne:
        customer:
            targetEntity: Elcodi\UserBundle\Entity\Customer
            inversedBy: carts
            joinColumn:
                name: customer_id
                referencedColumnName: id
                nullable: true

    oneToMany:
        cartLines:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\CartLineInterface
            mappedBy: cart
            cascade: ["all"]

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
