Elcodi\CartBundle\Entity\CartLine:
    type: entity
    repositoryClass: Elcodi\CartBundle\Repository\CartLineRepository
    table: cart_line
    fields:
        productAmount:
            column: product_amount
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        couponAmount:
            column: coupon_amount
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        amount:
            column: amount
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        quantity:
            column: quantity
            type: integer

    manyToOne:
        cart:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\CartInterface
            inversedBy: cartLines
            cascade: ["all"]
            joinColumn:
                name: cart_id
                referencedColumnName: id
                nullable: false

        product:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\ProductInterface
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
