Elcodi\CartBundle\Entity\CartLine:
    type: entity
    repositoryClass: Elcodi\CartBundle\Repository\CartLineRepository
    table: cart_line
    fields:
        priceProducts:
            column: price_products
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        priceCoupons:
            column: price_coupons
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        price:
            column: price
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        quantity:
            column: quantity
            type: integer

    manyToOne:
        cart:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\CartInterface
            inversedBy: cartLines
            cascade: ["all"]
            joinColumn:
                name: cart_id
                referencedColumnName: id
                nullable: false

        product:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\ProductInterface
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
