Elcodi\CartBundle\Entity\Order:
    type: entity
    repositoryClass: Elcodi\CartBundle\Repository\OrderRepository
    table: `order`
    fields:
        quantity:
            column: quantity
            type: integer
        priceProducts:
            column: price_products
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        priceCoupons:
            column: price_coupons
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        price:
            column: price
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    oneToOne:
        cart:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\CartInterface
            inversedBy: order
            joinColumn:
                name: cart_id
                referencedColumnName: id
                onDelete: "SET NULL"
                onUpdate: "CASCADE"
                nullable: true

        lastOrderHistory:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\OrderHistoryInterface
            joinColumn:
                name: last_order_history_id
                referencedColumnName: id
                nullable: true

    manyToOne:
        customer:
            targetEntity: Elcodi\UserBundle\Entity\Customer
            inversedBy: orders
            joinColumn:
                name: customer_id
                referencedColumnName: id
                nullable: false

    oneToMany:
        orderLines:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\OrderLineInterface
            mappedBy: order
            cascade: ["all"]
        orderHistories:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\OrderHistoryInterface
            mappedBy: order
            cascade: ["all"]

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
