Elcodi\CartBundle\Entity\OrderHistory:
    type: entity
    repositoryClass: Elcodi\CartBundle\Repository\OrderHistoryRepository
    table: order_history
    fields:
        state:
            column: state
            type: string
            length: 255
            nullable: false
        description:
            column: description
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    manyToOne:
        order:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\OrderInterface
            inversedBy: orderHistories
            cascade: [ all ]
            joinColumn:
                name: order_id
                referencedColumnName: id
                nullable: false

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
