parameters:

    #
    # EventDispatchers
    #
    elcodi.core.cart.event_dispatcher.cart.class: Elcodi\Component\Cart\EventDispatcher\CartEventDispatcher
    elcodi.core.cart.event_dispatcher.cart_line.class: Elcodi\Component\Cart\EventDispatcher\CartLineEventDispatcher
    elcodi.core.cart.event_dispatcher.order.class: Elcodi\Component\Cart\EventDispatcher\OrderEventDispatcher
    elcodi.core.cart.event_dispatcher.order_line.class: Elcodi\Component\Cart\EventDispatcher\OrderLineEventDispatcher

    #
    # Services
    #
    elcodi.core.cart.service.cart_manager.class: Elcodi\Component\Cart\Services\CartManager
    elcodi.core.cart.service.cart_session_manager.class: Elcodi\Component\Cart\Services\CartSessionManager

    #
    # Transformers
    #
    elcodi.core.cart.transformer.cart_order.class: Elcodi\Component\Cart\Transformer\CartOrderTransformer
    elcodi.core.cart.transformer.cart_line_order_line.class: Elcodi\Component\Cart\Transformer\CartLineOrderLineTransformer

    #
    # Event Listeners
    #
    elcodi.core.cart.event_listener.cart.class: Elcodi\Component\Cart\EventListener\CartEventListener
    elcodi.core.cart.event_listener.order.class: Elcodi\Component\Cart\EventListener\OrderEventListener
    elcodi.core.cart.event_listener.order_machine.class: Elcodi\Component\Cart\EventListener\OrderMachineEventListener
    elcodi.core.cart.event_listener.cart_session.class: Elcodi\Component\Cart\EventListener\CartSessionEventListener

    #
    # Factories
    #
    elcodi.core.cart.factory.cart.class: Elcodi\Component\Cart\Factory\CartFactory
    elcodi.core.cart.factory.order.class: Elcodi\Component\Cart\Factory\OrderFactory
    elcodi.core.cart.factory.cart_line.class: Elcodi\Component\Cart\Factory\CartLineFactory
    elcodi.core.cart.factory.order_line.class: Elcodi\Component\Cart\Factory\OrderLineFactory

    #
    # Wrappers
    #
    elcodi.core.cart.wrapper.cart_wrapper.class: Elcodi\Component\Cart\Wrapper\CartWrapper
