parameters:

    #
    # EventDispatchers
    #
    elcodi.event_dispatcher.cart.class: Elcodi\Component\Cart\EventDispatcher\CartEventDispatcher
    elcodi.event_dispatcher.cart_line.class: Elcodi\Component\Cart\EventDispatcher\CartLineEventDispatcher
    elcodi.event_dispatcher.order.class: Elcodi\Component\Cart\EventDispatcher\OrderEventDispatcher
    elcodi.event_dispatcher.order_line.class: Elcodi\Component\Cart\EventDispatcher\OrderLineEventDispatcher

    #
    # Services
    #
    elcodi.cart_manager.class: Elcodi\Component\Cart\Services\CartManager
    elcodi.cart_session_manager.class: Elcodi\Component\Cart\Services\CartSessionManager

    #
    # Transformers
    #
    elcodi.transformer.cart_order.class: Elcodi\Component\Cart\Transformer\CartOrderTransformer
    elcodi.transformer.cart_line_order_line.class: Elcodi\Component\Cart\Transformer\CartLineOrderLineTransformer

    #
    # Event Listeners
    #
    elcodi.event_listener.cart_load.class: Elcodi\Component\Cart\EventListener\CartLoadEventListener
    elcodi.event_listener.order_creation.class: Elcodi\Component\Cart\EventListener\OrderCreationEventListener
    elcodi.event_listener.order_line_creation.class: Elcodi\Component\Cart\EventListener\OrderLineCreationEventListener
    elcodi.event_listener.cart_session.class: Elcodi\Component\Cart\EventListener\CartSessionEventListener
    elcodi.event_listener.limit_negative_carts.class: Elcodi\Component\Cart\EventListener\LimitNegativeCartsListener

    #
    # Factories
    #
    elcodi.factory.cart.class: Elcodi\Component\Cart\Factory\CartFactory
    elcodi.factory.order.class: Elcodi\Component\Cart\Factory\OrderFactory
    elcodi.factory.cart_line.class: Elcodi\Component\Cart\Factory\CartLineFactory
    elcodi.factory.order_line.class: Elcodi\Component\Cart\Factory\OrderLineFactory

    #
    # Wrappers
    #
    elcodi.cart_wrapper.class: Elcodi\Component\Cart\Wrapper\CartWrapper
