services:

    #
    # Event Listeners
    #
    elcodi.core.cart.event_listener.cart:
        class: %elcodi.core.cart.event_listener.cart.class%
        arguments:
            order_manager: @elcodi.core.cart.service.cart_manager
            entity_manager: @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: cart.oncheck, method: onCartCheck }
            - { name: kernel.event_listener, event: cart.onload, method: onCartLoad }

    elcodi.core.cart.event_listener.order_line_state:
        class: %elcodi.core.cart.event_listener.order_line_state.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            event_dispatcher: @event_dispatcher
            order_history_factory: @elcodi.core.cart.factory.order_history
        tags:
            - { name: kernel.event_listener, event: orderlinestate.postchange, method: onOrderLineStatePostChange }

    elcodi.core.cart.event_listener.session:
        class: %elcodi.core.cart.event_listener.session.class%
        arguments:
            session: @session
            session_field_name: %elcodi.core.cart.session_field_name%
        tags:
            - { name: kernel.event_listener, event: cart.postload, method: onCartPostLoad}
