services:

    #
    # Event Listeners
    #
    elcodi.event_listener.cart_load:
        class: %elcodi.event_listener.cart_load.class%
        arguments:
            - @elcodi.object_manager.cart
            - @elcodi.event_dispatcher.cart
            - @elcodi.cart.manager
            - @elcodi.wrapper.currency
            - @elcodi.converter.currency
            - @elcodi.manager.configuration
        tags:
            - { name: kernel.event_listener, event: cart.preload, method: checkCartIntegrity, priority: 0 }
            - { name: kernel.event_listener, event: cart.onload, method: loadCartPrices, priority: 16 }
            - { name: kernel.event_listener, event: cart.onload, method: saveCart, priority: 0 }
            - { name: kernel.event_listener, event: cart.onload, method: loadCartQuantities, priority: 16 }

    elcodi.event_listener.limit_negative_carts:
        class: %elcodi.event_listener.limit_negative_carts.class%
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: limitCartAmount, priority: -255 }

    elcodi.event_listener.order_creation:
        class: %elcodi.event_listener.order_creation.class%
        arguments:
            - @elcodi.object_manager.order
            - @elcodi.object_manager.cart
        tags:
            - { name: kernel.event_listener, event: order.oncreated, method: saveOrder, priority: 0}
            - { name: kernel.event_listener, event: order.oncreated, method: setCartAsOrdered, priority: -16 }

    elcodi.event_listener.order_line_creation:
        class: %elcodi.event_listener.order_line_creation.class%
        arguments:
            - @elcodi.object_manager.product
            - @elcodi.object_manager.product_variant
        tags:
            - { name: kernel.event_listener, event: order_line.oncreated, method: updateStock, priority: 0}

    elcodi.event_listener.cart_session:
        class: %elcodi.event_listener.cart_session.class%
        arguments:
            - @elcodi.session_manager.cart
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: saveCartInSession, priority: -2 }

    elcodi.event_listener.address_clone:
        class: %elcodi.event_listener.address_clone.class%
        arguments:
            cart_repository: @elcodi.repository.cart
            cart_object_manager: @elcodi.object_manager.cart
        tags:
            - { name: kernel.event_listener, event: address.onclone, method: updateCarts, priority: 0}
