services:

    #
    # Event Listeners
    #
    elcodi.core.cart.event_listener.cart:
        class: %elcodi.core.cart.event_listener.cart.class%
        arguments:
            cart_manager: @elcodi.core.cart.service.cart_manager
            cart_entity_manager: @elcodi.manager.cart
        tags:
            - { name: kernel.event_listener, event: cart.oncheck, method: onCartCheck }
            - { name: kernel.event_listener, event: cart.onload, method: onCartLoad }
            - { name: kernel.event_listener, event: order.postcreated, method: postOrderCreated }

    elcodi.core.cart.event_listener.order_line_state:
        class: %elcodi.core.cart.event_listener.order_line_state.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            event_dispatcher: @event_dispatcher
            order_history_factory: @elcodi.core.cart.factory.order_history
        tags:
            - { name: kernel.event_listener, event: orderlinestate.postchange, method: onOrderLineStatePostChange }

    elcodi.core.cart.event_listener.cart_session:
        class: %elcodi.core.cart.event_listener.cart_session.class%
        arguments:
            cart_session_manager: @elcodi.cart_session_manager
        tags:
            - { name: kernel.event_listener, event: cart.postload, method: onCartPostLoad}

    elcodi.core.cart.event_listener.cart_load:
        class: %elcodi.core.cart.event_listener.cart_load.class%
        arguments:
            container: @service_container
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }
