services:

    #
    # Event Listeners
    #
    elcodi.core.cart.event_listener.cart_load:
        class: %elcodi.core.cart.event_listener.cart_load.class%
        arguments:
            cart_entity_manager: @elcodi.object_manager.cart
            cart_event_dispatcher: @elcodi.cart_event_dispatcher
            cart_manager: @elcodi.core.cart.service.cart_manager
            currency_wrapper: @elcodi.currency_wrapper
            currency_converter: @elcodi.currency_converter
        tags:
            - { name: kernel.event_listener, event: cart.preload, method: checkCartIntegrity, priority: 0 }
            - { name: kernel.event_listener, event: cart.onload, method: loadCartPrices, priority: 16 }
            - { name: kernel.event_listener, event: cart.onload, method: saveCart, priority: 0 }
            - { name: kernel.event_listener, event: cart.onload, method: loadCartQuantities, priority: -16 }

    elcodi.core.cart.event_listener.order_creation:
        class: %elcodi.core.cart.event_listener.order_creation.class%
        arguments:
            order_entity_manager: @elcodi.object_manager.order
            cart_entity_manager: @elcodi.object_manager.cart
        tags:
            - { name: kernel.event_listener, event: order.oncreated, method: saveOrder, priority: 0}
            - { name: kernel.event_listener, event: order.oncreated, method: setCartAsOrdered, priority: -16 }

    elcodi.core.cart.event_listener.order_line_creation:
        class: %elcodi.core.cart.event_listener.order_line_creation.class%
        arguments:
            product_object_manager: @elcodi.object_manager.product
            variant_object_manager: @elcodi.object_manager.product_variant
        tags:
            - { name: kernel.event_listener, event: order_line.oncreated, method: updateStock, priority: 0}

    elcodi.core.cart.event_listener.cart_session:
        class: %elcodi.core.cart.event_listener.cart_session.class%
        arguments:
            cart_session_manager: @elcodi.cart_session_manager
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: saveCartInSession, priority: -2 }
