services:

    #
    # EventDispatchers
    #
    elcodi.cart_event_dispatcher:
        class: %elcodi.cart_event_dispatcher.class%
        parent: elcodi.core.core.event_dispatcher.abstract

    elcodi.cart_line_event_dispatcher:
        class: %elcodi.cart_line_event_dispatcher.class%
        parent: elcodi.core.core.event_dispatcher.abstract

    elcodi.order_event_dispatcher:
        class: %elcodi.order_event_dispatcher.class%
        parent: elcodi.core.core.event_dispatcher.abstract

    elcodi.order_line_event_dispatcher:
        class: %elcodi.order_line_event_dispatcher.class%
        parent: elcodi.core.core.event_dispatcher.abstract
