services:

    #
    # EventDispatchers
    #
    elcodi.core.cart.event_dispatcher.cart:
        class: %elcodi.core.cart.event_dispatcher.cart.class%
        parent: elcodi.core.core.event_dispatcher.abstract

    elcodi.cart_event_dispatcher:
        alias: elcodi.core.cart.event_dispatcher.cart

    elcodi.core.cart.event_dispatcher.cart_line:
        class: %elcodi.core.cart.event_dispatcher.cart_line.class%
        parent: elcodi.core.core.event_dispatcher.abstract

    elcodi.cart_line_event_dispatcher:
        alias: elcodi.core.cart.event_dispatcher.cart_line

    elcodi.core.cart.event_dispatcher.order:
        class: %elcodi.core.cart.event_dispatcher.order.class%
        parent: elcodi.core.core.event_dispatcher.abstract

    elcodi.order_event_dispatcher:
        alias: elcodi.core.cart.event_dispatcher.order

    elcodi.core.cart.event_dispatcher.order_line:
        class: %elcodi.core.cart.event_dispatcher.order_line.class%
        parent: elcodi.core.core.event_dispatcher.abstract

    elcodi.order_line_event_dispatcher:
        alias: elcodi.core.cart.event_dispatcher.order_line
