services:

    #
    # Factories
    #

    #
    # Factory for entity cart
    #
    elcodi.core.cart.factory.cart:
        class: %elcodi.core.cart.factory.cart.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.cart.entity.cart.class%"]]

    elcodi.factory.cart:
        alias: elcodi.core.cart.factory.cart

    #
    # Factory for entity order
    #
    elcodi.core.cart.factory.order:
        class: %elcodi.core.cart.factory.order.class%
        arguments:
            order_state_transition_machine_manager: @elcodi.core.cart.order_state_transition_machine.machine_manager
        calls:
            - [setEntityNamespace, ["%elcodi.core.cart.entity.order.class%"]]

    elcodi.factory.order:
        alias: elcodi.core.cart.factory.order

    #
    # Factory for entity cart_line
    #
    elcodi.core.cart.factory.cart_line:
        class: %elcodi.core.cart.factory.cart_line.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.cart.entity.cart_line.class%"]]

    elcodi.factory.cart_line:
        alias: elcodi.core.cart.factory.cart_line

    #
    # Factory for entity order_line
    #
    elcodi.core.cart.factory.order_line:
        class: %elcodi.core.cart.factory.order_line.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.cart.entity.order_line.class%"]]

    elcodi.factory.order_line:
        alias: elcodi.core.cart.factory.order_line
