services:

    #
    # Factories
    #

    #
    # Factory for entity cart
    #
    elcodi.factory.cart:
        class: %elcodi.factory.cart.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.cart.class%"]]

    #
    # Factory for entity order
    #
    elcodi.factory.order:
        class: %elcodi.factory.order.class%
        arguments:
            - @elcodi.order.payment_states_machine.manager
            - @elcodi.order.shipping_states_machine.manager
        calls:
            - [setEntityNamespace, ["%elcodi.entity.order.class%"]]

    #
    # Factory for entity cart_line
    #
    elcodi.factory.cart_line:
        class: %elcodi.factory.cart_line.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.cart_line.class%"]]

    #
    # Factory for entity order_line
    #
    elcodi.factory.order_line:
        class: %elcodi.factory.order_line.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.order_line.class%"]]
