services:

    #
    # Order State Transition Machine services
    #
    elcodi.core.cart.order_state_transition_machine.state_line_factory:
        class: %elcodi.core.state_transition_machine.factory.state_line.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.cart.entity.order_state_line.class%"]]

    elcodi.core.cart.order_state_transition_machine.machine_builder:
        class: %elcodi.core.state_transition_machine.service.machine_builder.class%
        arguments:
            machine_factory: @elcodi.core.state_transition_machine.factory.machine
            identifier: %elcodi.core.cart.order_state_transition_machine_identifier%
            configuration: %elcodi.core.cart.order_state_transition_machine_states%
            point_of_entry: %elcodi.core.cart.order_state_transition_machine_point_of_entry%

    elcodi.core.cart.order_state_transition_machine.machine:
        class: %elcodi.core.state_transition_machine.service.machine.class%
        factory_service: elcodi.core.cart.order_state_transition_machine.machine_builder
        factory_method: compile

    elcodi.core.cart.order_state_transition_machine.factory.order_state_line:
        class: %elcodi.core.state_transition_machine.factory.state_line.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.state_transition_machine.entity.state_line.class%"]]

    elcodi.factory.state_line:
        alias: elcodi.core.state_transition_machine.factory.state_line

    elcodi.core.cart.order_state_transition_machine.machine_manager:
        class: %elcodi.core.state_transition_machine.service.machine_manager.class%
        arguments:
            machine: @elcodi.core.cart.order_state_transition_machine.machine
            event_dispatcher: @event_dispatcher
            state_line_factory: @elcodi.core.cart.order_state_transition_machine.state_line_factory

    elcodi.order_state_transition_machine:
        alias: elcodi.core.cart.order_state_transition_machine.machine_manager
