services:

    #
    # Managers
    #
    elcodi.core.cart.manager.cart:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            cart_namespace: %elcodi.core.cart.entity.cart.class%

    elcodi.manager.cart:
        alias: elcodi.core.cart.manager.cart

    elcodi.core.cart.manager.cart_line:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            cart_namespace: %elcodi.core.cart.entity.cart.class%

    elcodi.manager.cart_line:
        alias: elcodi.core.cart.manager.cart_line
