services:

    #
    # Object Managers
    #
    elcodi.object_manager.cart:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.cart.entity.cart.class% ]

    elcodi.object_manager.cart_line:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.cart.entity.cart.class% ]

    elcodi.object_manager.order:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.cart.entity.order.class% ]

    elcodi.object_manager.order_line:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.cart.entity.order_line.class% ]

    elcodi.object_manager.order_state_line:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.cart.entity.order_state_line.class% ]
