services:

    #
    # Repositories
    #

    #
    # Repository for entity cart
    #
    elcodi.repository.cart:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.cart.entity.cart.class% ]

    #
    # Repository for entity order
    #
    elcodi.repository.order:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.cart.entity.order.class% ]

    #
    # Repository for entity cart_line
    #
    elcodi.repository.cart_line:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.cart.entity.cart_line.class% ]

    #
    # Repository for entity order_line
    #
    elcodi.repository.order_line:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.cart.entity.order_line.class% ]

    #
    # Repository for entity order_history
    #
    elcodi.repository.order_state_line:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.cart.entity.order_state_line.class% ]
