services:

    #
    # Services
    #
    elcodi.cart.manager:
        class: %elcodi.cart.manager.class%
        arguments:
            - @elcodi.event_dispatcher.cart
            - @elcodi.event_dispatcher.cart_line
            - @elcodi.factory.cart
            - @elcodi.factory.cart_line

    elcodi.session_manager.cart:
        class: %elcodi.session_manager.cart.class%
        arguments:
            - @session
            - %elcodi.core.cart.cart_session_field_name%
            - %elcodi.core.cart.cart_save_in_session%

    #
    # Wrappers
    #
    elcodi.wrapper.cart:
        class: %elcodi.wrapper.cart.class%
        arguments:
            - @elcodi.event_dispatcher.cart
            - @elcodi.session_manager.cart
            - @elcodi.repository.cart
            - @elcodi.factory.cart
            - @elcodi.wrapper.customer
