services:

    #
    # Order state machine for Payment
    #
    elcodi.order.payment_states_machine.builder:
        class: %elcodi.state_transition_machine.machine_builder.class%
        arguments:
            - @elcodi.factory.state_transition_machine
            - %elcodi.order.payment_states_machine.identifier%
            - %elcodi.order.payment_states_machine.states%
            - %elcodi.order.payment_states_machine.point_of_entry%

    elcodi.order.payment_states_machine:
        class: %elcodi.state_transition_machine.machine.class%
        factory_service: elcodi.order.payment_states_machine.builder
        factory_method: compile

    elcodi.order.payment_states_machine.manager:
        class: %elcodi.state_transition_machine.machine_manager.class%
        arguments:
            - @elcodi.order.payment_states_machine
            - @event_dispatcher
            - @elcodi.factory.state_transition_machine_state_line


    #
    # Order state machine for Shipping
    #
    elcodi.order.shipping_states_machine.builder:
        class: %elcodi.state_transition_machine.machine_builder.class%
        arguments:
            - @elcodi.factory.state_transition_machine
            - %elcodi.order.shipping_states_machine.identifier%
            - %elcodi.order.shipping_states_machine.states%
            - %elcodi.order.shipping_states_machine.point_of_entry%

    elcodi.order.shipping_states_machine:
        class: %elcodi.state_transition_machine.machine.class%
        factory_service: elcodi.order.shipping_states_machine.builder
        factory_method: compile

    elcodi.order.shipping_states_machine.manager:
        class: %elcodi.state_transition_machine.machine_manager.class%
        arguments:
            - @elcodi.order.shipping_states_machine
            - @event_dispatcher
            - @elcodi.factory.state_transition_machine_state_line
